Pac 38 orika
bcaban/parcel-management-system pull request #10
Opened 2020-12-15 16:19 UTC by tomoicki

Renamed and refactored to OrikaMapper. Left old mapper cuz i wasnt sure about its deletion.
Please review. If it still needs any changes please let me know.

2020-12-15 16:30 UTC, TheFlyingKeyboard requested changes

2020-12-15 16:30 UTC, TheFlyingKeyboard commented on backend/src/main/java/com/webappsbusters/parcelmanagement/controller/ParcelController.java
>      private final ParcelMapper parcelMapper;
I think we should remove this old mapper, as it is not needed now. Remove ParcelMapper.class and this field

2020-12-15 16:30 UTC, TheFlyingKeyboard commented on backend/src/main/java/com/webappsbusters/parcelmanagement/mapper/OrikaAttemptTest.java
> +    }
I think we don't need this class, as we know the new mapper works

2020-12-15 16:30 UTC, TheFlyingKeyboard commented on backend/src/main/java/com/webappsbusters/parcelmanagement/controller/ParcelController.java
> +                        orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND)),ParcelDto.class);
please reformat - add space after  ","

2020-12-15 16:30 UTC, TheFlyingKeyboard commented on backend/pom.xml
> +			<version>1.5.4</version>
Please extract version to properties - intellij can do that, it is in right click -> refactor -> extract property or introduce property

2020-12-16 11:54 UTC, TheFlyingKeyboard approved these changes

2020-12-16 14:34 UTC, tomoicki commented
Można już zrobić "Merge pull request" czy coś posuje?

2020-12-16 15:03 UTC, joakrzem approved these changes

2020-12-16 15:10 UTC, merged